import { strict as assert } from 'assert';
import { describe, it } from 'mocha';
import {
    AUTO_ROUTER_RULES,
    applyDeterministicRules,
    contentLines,
    hasContentLines,
} from '../../../services/router/deterministicRules';
import { buildStagedDiff, routeAutoGeneration } from '../../../services/router/autoRouter';
import {
    DEFAULT_COVERAGE_TARGET,
    RouterArtifactError,
    resetRouterArtifactCache,
} from '../../../services/router/modelArtifact';
import * as routerArtifact from '../../../services/router/modelArtifact';
import type { DiffData } from '../../../services/git/gitTypes';

/**
 * The deterministic rule layer: changes whose diff carries nothing a message writer can read are routed
 * Fast before the model is consulted.
 *
 * The case table below is deliberately small and hand-written. The exhaustive fixture — 91 cases of
 * harvested image commits, labelled corpus cases the rules do and do not claim, and script-built near
 * misses — lives in the router benchmark (`ts/rule-cases.json`, generated by `scripts/gen_rule_cases.py`),
 * where `ts/rule-parity.ts` compares every verdict and the line model against the Python reference. What
 * this suite owns is the *integration*: that a rule hit short-circuits the artifact, that near misses fall
 * through to the model, and that the diff-line contract holds on binary payloads.
 */

interface RuleCase {
    name: string;
    source: string;
    files: string[];
    diff: string;
    expectedRule: string | null;
    expectedRoute: 'fast' | 'deep';
    note?: string;
}

const RULE_CASES: RuleCase[] = [
    {
        name: "flask-5892a6f2",
        source: "git:flask@5892a6f2c5ae",
        files: ["docs/_static/pycharm-runconfig.png"],
        diff: "diff --git a/docs/_static/pycharm-runconfig.png b/docs/_static/pycharm-runconfig.png\nindex 7e2de581..abfccd7a 100644\nBinary files a/docs/_static/pycharm-runconfig.png and b/docs/_static/pycharm-runconfig.png differ\n",
        expectedRule: "binary-asset-only",
        expectedRoute: "fast",
    },
    {
        name: "flask-41f5ad9b",
        source: "git:flask@41f5ad9b1539",
        files: ["docs/_static/no.png", "docs/_static/yes.png"],
        diff: "diff --git a/docs/_static/no.png b/docs/_static/no.png\nnew file mode 100644\nindex 00000000..4ac1083d\nBinary files /dev/null and b/docs/_static/no.png differ\ndiff --git a/docs/_static/yes.png b/docs/_static/yes.png\nnew file mode 100644\nindex 00000000..ac27c4e1\nBinary files /dev/null and b/docs/_static/yes.png differ\n",
        expectedRule: "binary-asset-only",
        expectedRoute: "fast",
    },
    {
        name: "gjson-aed5ee95",
        source: "git:gjson@aed5ee957a1a",
        files: ["logo.png"],
        diff: "diff --git a/logo.png b/logo.png\nindex c7f17d0..17a8bbe 100644\nBinary files a/logo.png and b/logo.png differ\n",
        expectedRule: "binary-asset-only",
        expectedRoute: "fast",
    },
    {
        name: "joda-time-44efdb23",
        source: "git:joda-time@44efdb230cbd",
        files: ["JodaTime/src/site/resources/images/joda.png", "JodaTime/src/site/resources/images/jodatime.png"],
        diff: "diff --git a/JodaTime/src/site/resources/images/joda.png b/JodaTime/src/site/resources/images/joda.png\nnew file mode 100644\nindex 00000000..435df26a\nBinary files /dev/null and b/JodaTime/src/site/resources/images/joda.png differ\ndiff --git a/JodaTime/src/site/resources/images/jodatime.png b/JodaTime/src/site/resources/images/jodatime.png\nnew file mode 100644\nindex 00000000..4d5d6098\nBinary files /dev/null and b/JodaTime/src/site/resources/images/jodatime.png differ\n",
        expectedRule: "binary-asset-only",
        expectedRoute: "fast",
    },
    {
        name: "sinatra-2635a53d",
        source: "git:sinatra@2635a53d0f39",
        files: ["lib/sinatra/images/404.png", "lib/sinatra/images/500.png"],
        diff: "diff --git a/lib/sinatra/images/404.png b/lib/sinatra/images/404.png\nindex 902110e1..f16a914f 100644\nBinary files a/lib/sinatra/images/404.png and b/lib/sinatra/images/404.png differ\ndiff --git a/lib/sinatra/images/500.png b/lib/sinatra/images/500.png\nindex 57c84c3d..e08b17d9 100644\nBinary files a/lib/sinatra/images/500.png and b/lib/sinatra/images/500.png differ\n",
        expectedRule: "binary-asset-only",
        expectedRoute: "fast",
    },
    {
        name: "cobra-4dd4b25d-mixed",
        source: "git:cobra@4dd4b25de384",
        files: ["README.md", "assets/CobraMain.png"],
        diff: "diff --git a/README.md b/README.md\nindex 063f31a..592c0b8 100644\n--- a/README.md\n+++ b/README.md\n@@ -1,4 +1,4 @@\n-![cobra logo](https://cloud.githubusercontent.com/assets/173412/10886352/ad566232-814f-11e5-9cd0-aa101788c117.png)\n+![cobra logo](assets/CobraMain.png)\n \n Cobra is a library for creating powerful modern CLI applications.\n \ndiff --git a/assets/CobraMain.png b/assets/CobraMain.png\nnew file mode 100644\nindex 0000000..6f1b68a\nBinary files /dev/null and b/assets/CobraMain.png differ\n",
        expectedRule: null,
        expectedRoute: "deep",
        note: "real commit that changes a media file *and* text: the rule must stand down",
    },
    {
        name: "lock-npm",
        source: "script",
        files: ["package-lock.json"],
        diff: "diff --git a/package-lock.json b/package-lock.json\nindex 1111111..2222222 100644\n--- a/package-lock.json\n+++ b/package-lock.json\n@@ -1,3 +1,3 @@\n-  resolved: \"https://registry.example/pkg/-/pkg-1.0.0.tgz\"\n+  resolved: \"https://registry.example/pkg/-/pkg-1.1.0.tgz\"\n",
        expectedRule: "lockfile-only",
        expectedRoute: "fast",
    },
    {
        name: "lock-yarn",
        source: "script",
        files: ["yarn.lock"],
        diff: "diff --git a/yarn.lock b/yarn.lock\nindex 1111111..2222222 100644\n--- a/yarn.lock\n+++ b/yarn.lock\n@@ -1,3 +1,3 @@\n-  resolved: \"https://registry.example/pkg/-/pkg-1.0.0.tgz\"\n+  resolved: \"https://registry.example/pkg/-/pkg-1.1.0.tgz\"\n",
        expectedRule: "lockfile-only",
        expectedRoute: "fast",
    },
    {
        name: "submodule-bump",
        source: "script",
        files: ["vendor/third-party"],
        diff: "diff --git a/vendor/third-party b/vendor/third-party\nindex 1111111..2222222 160000\n--- a/vendor/third-party\n+++ b/vendor/third-party\n@@ -1 +1 @@\n-Subproject commit 1111111111111111111111111111111111111111\n+Subproject commit 2222222222222222222222222222222222222222\n",
        expectedRule: "submodule-bump-only",
        expectedRoute: "fast",
    },
    {
        name: "submodule-bump-vendor-path",
        source: "script",
        files: ["vendor/third-party"],
        diff: "diff --git a/vendor/third-party b/vendor/third-party\nindex 5555555..6666666 160000\n--- a/vendor/third-party\n+++ b/vendor/third-party\n@@ -1 +1 @@\n-Subproject commit 5555555555555555555555555555555555555555\n+Subproject commit 6666666666666666666666666666666666666666\n",
        expectedRule: "submodule-bump-only",
        expectedRoute: "fast",
        note: "vendor/ also matches the generated-artifact rule; submodule wins so the logged reason is exact",
    },
    {
        name: "binary-font",
        source: "script",
        files: ["assets/inter.woff2"],
        diff: "diff --git a/assets/inter.woff2 b/assets/inter.woff2\nnew file mode 100644\nindex 0000000..abc1234\nBinary files /dev/null and b/assets/inter.woff2 differ\n",
        expectedRule: "binary-asset-only",
        expectedRoute: "fast",
    },
    {
        name: "binary-delete-zip",
        source: "script",
        files: ["dist/archive.zip"],
        diff: "diff --git a/dist/archive.zip b/dist/archive.zip\ndeleted file mode 100644\nindex abc1234..0000000\nBinary files a/dist/archive.zip and /dev/null differ\n",
        expectedRule: "binary-asset-only",
        expectedRoute: "fast",
    },
    {
        name: "svg-hand-edited",
        source: "script",
        files: ["icons/logo.svg"],
        diff: "diff --git a/icons/logo.svg b/icons/logo.svg\nindex 1111111..2222222 100644\n--- a/icons/logo.svg\n+++ b/icons/logo.svg\n@@ -1,2 +1,2 @@\n <svg width=\"16\" height=\"16\">\n-  <path d=\"M0 0h8v8H0z\"/>\n+  <path d=\"M0 0h16v16H0z\"/>\n",
        expectedRule: null,
        expectedRoute: "deep",
        note: "a text diff means there is something to read, even for an image extension",
    },
    {
        name: "lock-plus-manifest",
        source: "script",
        files: ["package-lock.json", "package.json"],
        diff: "diff --git a/package-lock.json b/package-lock.json\nindex 1111111..2222222 100644\n--- a/package-lock.json\n+++ b/package-lock.json\n@@ -1,3 +1,3 @@\n-  resolved: \"https://registry.example/pkg/-/pkg-1.0.0.tgz\"\n+  resolved: \"https://registry.example/pkg/-/pkg-1.1.0.tgz\"\ndiff --git a/package.json b/package.json\nindex 3333333..4444444 100644\n--- a/package.json\n+++ b/package.json\n@@ -1,2 +1,3 @@\n line one\n+line two\n line three\n",
        expectedRule: null,
        expectedRoute: "deep",
    },
    {
        name: "submodule-plus-source",
        source: "script",
        files: ["vendor/third-party", "src/main.go"],
        diff: "diff --git a/vendor/third-party b/vendor/third-party\nindex 1111111..2222222 160000\n--- a/vendor/third-party\n+++ b/vendor/third-party\n@@ -1 +1 @@\n-Subproject commit 1111111111111111111111111111111111111111\n+Subproject commit 2222222222222222222222222222222222222222\ndiff --git a/src/main.go b/src/main.go\nindex 3333333..4444444 100644\n--- a/src/main.go\n+++ b/src/main.go\n@@ -1,2 +1,3 @@\n line one\n+line two\n line three\n",
        expectedRule: null,
        expectedRoute: "deep",
    },
    {
        name: "binary-patch-delta",
        source: "script",
        files: ["assets/logo.png"],
        diff: "diff --git a/assets/logo.png b/assets/logo.png\nindex 1111111..2222222 100644\nGIT binary patch\ndelta 42\n+loremipsum00000000000000\n-anotherline00000000000\n\n",
        expectedRule: null,
        expectedRoute: "deep",
        note: "a GIT binary patch delta can carry +/- payload lines; the rule stands down and the model decides",
    },
    {
        name: "empty-file-delete",
        source: "script",
        files: ["src/legacy.rs"],
        diff: "diff --git a/src/legacy.rs b/src/legacy.rs\ndeleted file mode 100644\nindex e69de29..0000000\n",
        expectedRule: null,
        expectedRoute: "deep",
        note: "empty-file delete has no content lines but is still a removal worth explaining",
    },
    {
        name: "rename-only",
        source: "script",
        files: ["src/handler.ts"],
        diff: "diff --git a/src/handlers/handler.ts b/src/handler.ts\nsimilarity index 100%\nrename from src/handlers/handler.ts\nrename to src/handler.ts\n",
        expectedRule: null,
        expectedRoute: "deep",
        note: "rejected class: the judge preferred the pipeline in 2/2 such cases",
    },
];

/** The fixture's media diffs are whole commits; routing sees every changed file, not just the assets. */
function diffsOf(testCase: RuleCase): DiffData[] {
    const blocks = testCase.diff
        .split(/(?=^diff --git )/m)
        .filter(block => block.startsWith('diff --git'));
    assert.equal(blocks.length, testCase.files.length, `${testCase.name}: one block per changed file`);
    return blocks.map((block, index) => ({
        fileName: testCase.files[index],
        status: 'modified',
        diffHunks: [],
        // A non-final block is a slice of the original text, so it carries no terminator; leaving the
        // newline in would be read as a content blank line and shift the diff by one line.
        rawDiff: index === blocks.length - 1 ? block : block.replace(/\n$/u, ''),
    }));
}

describe('Deterministic routing rules', () => {
    it('claims exactly the classes the reference implementation claims', () => {
        const mismatches = RULE_CASES
            .map(testCase => ({
                testCase,
                rule: applyDeterministicRules(testCase.diff, testCase.files),
            }))
            .filter(({ testCase, rule }) => rule !== testCase.expectedRule);

        assert.deepEqual(
            mismatches.map(({ testCase, rule }) => `${testCase.name}: got ${rule} want ${testCase.expectedRule}`),
            [],
            `${RULE_CASES.length} cases`,
        );
        assert.equal(RULE_CASES.filter(testCase => testCase.expectedRule).length, 11);
    });

    it('routes rule hits without a model score and leaves everything else to the model', () => {
        for (const testCase of RULE_CASES) {
            const decision = routeAutoGeneration(diffsOf(testCase));
            if (testCase.expectedRule) {
                assert.equal(decision.route, 'fast', testCase.name);
                assert.equal(decision.reason, 'rule', testCase.name);
                assert.equal(decision.rule, testCase.expectedRule, testCase.name);
                // No model was consulted, so there is no score, no threshold and no artifact identity.
                assert.equal(decision.probabilityDirect, null, testCase.name);
                assert.equal(decision.directThreshold, null, testCase.name);
                assert.equal(decision.artifactSha256, null, testCase.name);
                assert.equal(decision.coverageTarget, DEFAULT_COVERAGE_TARGET, testCase.name);
                assert.equal(decision.failure, undefined, testCase.name);
            } else {
                // `expectedRoute: 'deep'` means "the rule stood down"; which route the model then picks is
                // its own business and is covered by the router suite.
                assert.equal(decision.reason, 'model', `${testCase.name}: a rule must not claim this case`);
                assert.equal(decision.rule, undefined, testCase.name);
            }
        }
    });

    it('routes real harvested image commits to Fast without scoring them', () => {
        const harvested = RULE_CASES.filter(testCase => testCase.source.startsWith('git:') && testCase.expectedRule);
        assert.ok(harvested.length >= 3, `harvested media-only commits: ${harvested.length}`);

        for (const testCase of harvested) {
            const decision = routeAutoGeneration(diffsOf(testCase));
            assert.equal(decision.reason, 'rule', `${testCase.name} (${testCase.source})`);
            assert.equal(decision.rule, 'binary-asset-only', testCase.name);
        }
    });

    it('stands down on near misses, including a real commit that mixes a media file with text', () => {
        const negatives = RULE_CASES.filter(testCase => testCase.expectedRule === null);
        assert.ok(negatives.length >= 5, `negatives: ${negatives.length}`);
        assert.ok(
            negatives.some(testCase => testCase.name.endsWith('-mixed')),
            'the real mixed commit must be in the table',
        );

        for (const testCase of negatives) {
            assert.equal(applyDeterministicRules(testCase.diff, testCase.files), null, testCase.name);
            assert.equal(routeAutoGeneration(diffsOf(testCase)).reason, 'model', testCase.name);
        }
    });

    it('keeps routing rule hits even when the model cannot be loaded', () => {
        // The rule layer runs before the artifact is touched, so a broken payload must not change how a
        // rule-hit change is routed. `loadRouterArtifact` is swapped for a throwing stub — the module
        // object is shared with the compiled `autoRouter`, which calls it through the namespace.
        const ruleCase = RULE_CASES.find(testCase => testCase.expectedRule === 'binary-asset-only')!;
        const modelCase = RULE_CASES.find(testCase => testCase.expectedRule === null)!;
        const original = routerArtifact.loadRouterArtifact;
        const mutable = routerArtifact as { loadRouterArtifact: typeof original };
        mutable.loadRouterArtifact = () => {
            throw new RouterArtifactError('tampered router artifact: GCM tag mismatch');
        };

        try {
            const ruleDecision = routeAutoGeneration(diffsOf(ruleCase));
            assert.equal(ruleDecision.route, 'fast');
            assert.equal(ruleDecision.reason, 'rule');
            assert.equal(ruleDecision.rule, 'binary-asset-only');
            assert.equal(ruleDecision.artifactSha256, null);
            assert.equal(ruleDecision.failure, undefined);

            const modelDecision = routeAutoGeneration(diffsOf(modelCase));
            assert.equal(modelDecision.route, 'deep');
            assert.equal(modelDecision.reason, 'fallback');
            assert.match(String(modelDecision.failure), /GCM tag mismatch/u);
        } finally {
            mutable.loadRouterArtifact = original;
            resetRouterArtifactCache();
        }
    });

    it('models diff lines the way the reference does', () => {
        const binaryPatch = 'diff --git a/a.png b/a.png\nnew file mode 100644\nindex 0000000..abc\nBinary files /dev/null and b/a.png differ\n';
        const deltaPayload = 'diff --git a/a.png b/a.png\nindex 111..222 100644\nGIT binary patch\ndelta 42\n+payloadline\n-anotherpayload\n\n';
        const headersOnly = 'diff --git a/a.txt b/a.txt\nold mode 100644\nnew mode 100755\n--- a/a.txt\n+++ b/a.txt\n';
        const crlf = 'diff --git a/a.txt b/a.txt\r\n--- a/a.txt\r\n+++ b/a.txt\r\n@@ -1 +1 @@\r\n-old line\r\n+new line\r\n';

        assert.equal(hasContentLines(binaryPatch), false);
        assert.equal(hasContentLines(deltaPayload), true, 'a binary delta payload can look like content; stand down');
        assert.equal(contentLines(deltaPayload).length, 2);
        assert.equal(hasContentLines(headersOnly), false, '--- and +++ are headers, not content');
        assert.equal(hasContentLines(crlf), true);
        assert.equal(hasContentLines(''), false);
    });

    it('rebuilds every case diff from its blocks without losing a line', () => {
        for (const testCase of RULE_CASES) {
            assert.equal(buildStagedDiff(diffsOf(testCase)), testCase.diff, testCase.name);
        }
    });

    it('keeps the rule table ordered, described and free of rejected classes', () => {
        // `generated-artifact-only` was dropped after its own measurement came back 0/1 (build output is
        // readable text); the list below is the shipped set, not the candidate set.
        assert.deepEqual(
            AUTO_ROUTER_RULES.map(rule => rule.name),
            ['binary-asset-only', 'lockfile-only', 'submodule-bump-only'],
        );
        for (const rule of AUTO_ROUTER_RULES) {
            assert.ok(rule.description.length > 0, rule.name);
        }
    });
});
